[package]
name = "velvet"
version = "0.4.1"
authors = ["Seaton Ullberg <seatonullberg@gmail.com>"]
edition = "2018"
repository = "https://github.com/seatonullberg/velvet"
description = "Classical atomistic simulation engine with a focus on user-friendliness and extensibility"
license = "MIT"
keywords = [
    "chemistry",
    "materials-science",
    "molecular-dynamics",
    "physics",
]
categories = [
    "science",
    "simulation",
]

[workspace]
members = [
    "crates/cli",
    "crates/core",
    "crates/external-data",
    "crates/test-utils",
]

[dependencies]
velvet-core = { path = "crates/core", version = "0.4.1" }
velvet-external-data = { path = "crates/external-data", version = "0.1.0" }

hdf5 = { version = "0.7", optional = true }
hdf5-sys = { version = "0.7", optional = true }

[dev-dependencies]
approx = "0.4"
criterion = "0.3"
nalgebra = "0.23"
velvet-test-utils = { path = "crates/test-utils" }

[features]
default = []
hdf5-output = ["velvet-core/hdf5-output", "hdf5", "hdf5-sys"]

[[bench]]
name = "integrator-benchmarks"
path = "benches/integrators.rs"
harness = false

[[bench]]
name = "pair-potential-benchmarks"
path = "benches/potentials/pair.rs"
harness = false

[[bench]]
name = "property-benchmarks"
path = "benches/properties.rs"
harness = false

[[bench]]
name = "thermostat-benchmarks"
path = "benches/thermostats.rs"
harness = false

[[bench]]
name = "velocity-distribution-benchmarks"
path = "benches/velocity_distributions.rs"
harness = false

[package.metadata.docs.rs]
features = ["hdf5-sys/static", "hdf5-sys/zlib"]