[package]
name = "velvet"
version = "0.1.0"
authors = ["Seaton Ullberg <seatonullberg@gmail.com>"]
edition = "2018"
description = "A tiny molecular dynamics simulator."
license = "MIT"
keywords = [
    "molecular-dynamics",
    "materials-science",
]
categories = [
    "science",
    "simulation",
]

[lib]
name = "velvet"
path = "src/lib.rs"

[[bin]]
name = "velvet"
path = "src/main.rs"


[package.metadata.docs.rs]
rustdoc-args = [ "--html-in-header", "katex-header.html" ]

[dependencies]
nalgebra = "0.21.1"