[package]
name = "velvet"
version = "0.1.0"
authors = ["Seaton Ullberg <seatonullberg@gmail.com>"]
edition = "2018"
description = "An experimental molecular dynamics engine with a focus on user-friendliness and extensibility."
license = "MIT"
keywords = [
    "chemistry",
    "materials-science",
    "molecular-dynamics",
    "physics",
]
categories = [
    "science",
    "simulation",
]

[workspace]
members = [
    "crates/app",
    "crates/convert",
    "crates/core",
]

[[bin]]
name = "velvet"
path = "crates/app/src/main.rs"

[dev-dependencies]
indicatif = "0.15"
log = "0.4"
plotters = "0.3.0"
pretty_env_logger = "0.4"
velvet-convert = { path = "crates/convert" }
velvet-core = { path = "crates/core" }