[package]
name = "velvet-core"
version = "0.1.0"
authors = ["Seaton Ullberg <seatonullberg@gmail.com>"]
description = "Core feature library for the Velvet simulation engine."
license = "MIT"
repository = "https://github.com/seatonullberg/velvet"
edition = "2018"

[dependencies]
nalgebra = {version = "0.23", features = ["serde-serialize"]}
rand = "0.7"
rand_distr = "0.3"
serde = {version = "1.0", features = ["derive"]}
strum = "0.20"
strum_macros = "0.20"
typetag = "0.1.6"

[dev-dependencies]
approx = "0.4"
ron = "0.6"