[package]
name = "velvet-core"
version = "0.1.0"
authors = ["Seaton Ullberg <seatonullberg@gmail.com>"]
description = "Core feature library for the Velvet simulation engine."
license = "MIT"
repository = "https://github.com/seatonullberg/velvet"
edition = "2018"

[dependencies]
nalgebra = {version = "0.23", features = ["serde-serialize"]}
serde = {version = "1.0", features = ["derive"]}

[dev-dependencies]
approx = "0.4"
ron = "0.6"