[book]
title = "The Velvet Molecular Dynamics Simulator"
authors = ["Seaton Ullberg"]
language = "en"

[rust]
edition = "2018"

[build]
# build in `docs` for automatic deployment to github pages
build-dir = "../docs/"
create-missing = false

[output.html]
preferred-dark-theme = "Ayu"
mathjax-support = true
git-repository-url = "https://github.com/seatonullberg/velvet"